### PR TITLE
heat map

### PR DESCRIPTION
**Pull request by jmmanley**
If you're interested, basically my same pull request from #9, post merging of #11. Happy coding !

### CODE REVIEW

**Comment by sakethramanujam** [comment]
I don't know why the code has some broken functionality coming to camera selection? Is it the same with you? Clarification needed on this before i can merge.

**Comment by jmmanley** [comment]
Can you clarify the issue you're having? Do you mean camera selection as in line 60: `video_capture = cv2.VideoCapture(0)`? Do you get an error? This runs fine for me. I hope this isn't a Mac vs. Windows issue, I have had this problem on other opencv projects.

**Comment by sakethramanujam** [comment]
I'm getting an assertion error. I know this is quite common when the opencv doesn't recognize the camera.

**Comment by sakethramanujam** [comment]
@jmmanley issue resolved.! I'm closing the pr for now. You're doing a great job. Please also look into newer issues

**Pull request closed without merging**
